# Generated by Django 4.1.4 on 2023-04-06 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('toc', models.CharField(max_length=100)),
                ('he', models.CharField(max_length=100)),
            ],
        ),
    ]
