# Generated by Django 4.1.4 on 2023-04-25 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_new_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('new', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.new')),
            ],
        ),
    ]
