# Generated by Django 4.1.4 on 2023-04-25 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='image',
        ),
    ]
